src/Entity/Guest.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GuestRepository")
 */
class Guest
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_approved;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getIsApproved(): ?bool
    {
        return $this->is_approved;
    }

    public function setIsApproved(?bool $is_approved): self
    {
        $this->is_approved = $is_approved;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/GuestType.php
<?php

namespace App\Form;

use App\Entity\Guest;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class GuestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('comment', TextareaType::class)  
	        -> add('Save', SubmitType::class, [
			'attr' =>[
			          'class'=>'btn btn-success'
			]
			]);	
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Guest::class,
        ]);
    }
}

src/Controller/GuestController.php
<?php

namespace App\Controller;

use App\Entity\Guest;
use App\Form\Guest1Type;
use App\Repository\GuestRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/guest")
 */
class GuestController extends AbstractController
{
    /**
     * @Route("/", name="guest_index", methods={"GET"})
     */
    public function index(GuestRepository $guestRepository): Response
    {
        return $this->render('guest/index.html.twig', [
            'guests' => $guestRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="guest_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $guest = new Guest();
        $form = $this->createForm(Guest1Type::class, $guest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($guest);
            $entityManager->flush();

            return $this->redirectToRoute('guest_index');
        }

        return $this->render('guest/new.html.twig', [
            'guest' => $guest,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="guest_show", methods={"GET"})
     */
    public function show(Guest $guest): Response
    {
        return $this->render('guest/show.html.twig', [
            'guest' => $guest,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="guest_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Guest $guest): Response
    {
        $form = $this->createForm(Guest1Type::class, $guest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('guest_index', [
                'id' => $guest->getId(),
            ]);
        }

        return $this->render('guest/edit.html.twig', [
            'guest' => $guest,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="guest_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Guest $guest): Response
    {
        if ($this->isCsrfTokenValid('delete'.$guest->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($guest);
            $entityManager->flush();
        }

        return $this->redirectToRoute('guest_index');
    }
}

templates/guest/_delete_form.html.twig
<form method="post" action="{{ path('guest_delete', {'id': guest.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ guest.id) }}">
    <button class="btn">Delete</button>
</form>

templates/guest/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/guest/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Guest{% endblock %}

{% block body %}
    <h1>Edit Guest</h1>

    {{ include('guest/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('guest_index') }}">back to list</a>

    {{ include('guest/_delete_form.html.twig') }}
{% endblock %}

templates/guest/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Guest index{% endblock %}

{% block body %}
    <h1>Guest index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Comment</th>
                <th>Is_approved</th>
                <th>User_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for guest in guests %}
            <tr>
                <td>{{ guest.id }}</td>
                <td>{{ guest.comment }}</td>
                <td>{{ guest.isApproved ? 'Yes' : 'No' }}</td>
                <td>{{ guest.userId }}</td>
                <td>
                    <a href="{{ path('guest_show', {'id': guest.id}) }}">show</a>
                    <a href="{{ path('guest_edit', {'id': guest.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('guest_new') }}">Create new</a>
{% endblock %}

templates/guest/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Guest{% endblock %}

{% block body %}
    <h1>Create new Guest</h1>

    {{ include('guest/_form.html.twig') }}

    <a href="{{ path('guest_index') }}">back to list</a>
{% endblock %}

templates/guest/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Guest{% endblock %}

{% block body %}
    <h1>Guest</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ guest.id }}</td>
            </tr>
            <tr>
                <th>Comment</th>
                <td>{{ guest.comment }}</td>
            </tr>
            <tr>
                <th>Is_approved</th>
                <td>{{ guest.isApproved ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ guest.userId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('guest_index') }}">back to list</a>

    <a href="{{ path('guest_edit', {'id': guest.id}) }}">edit</a>

    {{ include('guest/_delete_form.html.twig') }}
{% endblock %}